junos.pm: handle show chassis firmware bug for 11.x on EX - Wouter de Jong
The command to fail in rancid 3.x for this old stack, since a 'show chassis
firmware' on it returns the following :

rancid@AncientJuniperEX> show chassis firmware
fpc0:
--------------------------------------------------------------------------
error: the chassis-control subsystem is not running

fpc1:
--------------------------------------------------------------------------
Part                     Type       Version
FPC 0                    uboot      U-Boot 1.1.6 (Mar 28 2011 - 04:05:40) 1.0.0
                         loader     FreeBSD/PowerPC U-Boot bootstrap loader 2.4
FPC 1                    uboot      U-Boot 1.1.6 (Mar 28 2011 - 04:05:40) 1.0.0
                         loader     FreeBSD/PowerPC U-Boot bootstrap loader 2.4
FPC 2                    uboot      U-Boot 1.1.6 (Jun  5 2012 - 02:24:53) 1.0.0
                         loader     FreeBSD/PowerPC U-Boot bootstrap loader 2.4
FPC 3                    uboot      U-Boot 1.1.6 (Jun  5 2012 - 02:26:04) 1.0.0
                         loader     FreeBSD/PowerPC U-Boot bootstrap loader 2.4

fpc2:
--------------------------------------------------------------------------
error: the chassis-control subsystem is not running

fpc3:
--------------------------------------------------------------------------
Aborted! This command can only be used on the master routing engine.

{master:1}
rancid@AncientJuniperEX>


The reason this stack displays the error messages, seems to be that this old
Jun OS executes the command by default on all-members, instead of only on the
local (active RE) one, hence generating errors for the non-RE members.

If we execute the 'show chassis firmware local', the output is as expected
and rancid works fine.  However, in newer JunOS releases, the 'local' command
seems to have been phased out.